steps:
    - name: 'node:current-alpine'
      dir: 'frontend'
      entrypoint: 'npm'
      args: ['install']
    - name: 'node:current-alpine'
      dir: 'frontend'
      entrypoint: 'npm'
      args: ['run', 'build', '--production=true']
    - name: 'golang'
      dir: 'backend'
      args: ['go', 'build', '.']