version: '3'
services:
    db:
        image: postgres:latest
        environment: 
            - POSTGRES_PASSWORD
    server:
        build:
            context: .
            args: 
                - REACT_APP_FIREBASE_API_KEY=$REACT_APP_FIREBASE_API_KEY
                - REACT_APP_FIREBASE_AUTH_DOMAIN=$REACT_APP_FIREBASE_AUTH_DOMAIN
        volumes:
            - "c:\\users\\owner\\appdata\\roaming\\gcloud:/root/.config/gcloud"
        ports:
            - "3000:3000"
        links:
            - db
        environment: 
            - PORT=3000
            - DBCONNSTRING